name: Release

on:
  push:
    tags:
      - '*.*.*'

jobs:
  build:
    uses: ./.github/workflows/build.yaml
    with:
      deploy: true
    secrets:
      credentials_json: ${{ secrets.GCP_CREDENTIALS }}
