name: Staging

on:
  push:
    branches:
      - main
      - script-migration

jobs:
  build:
    uses: ./.github/workflows/build.yaml
    with:
      deploy: false
    secrets:
      credentials_json: ${{ secrets.GCP_CREDENTIALS }}
